name: app_analyzer_plugin
description: app_analyzer_plugin.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ">=1.8.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  analyzer: ">=4.5.0 <7.0.0"
  analyzer_plugin: ">=0.7.0 <0.12.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
