name: app_analyzer_plugin_loader
description: This pubspec determines the version of the analyzer plugin to load.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  app_analyzer_plugin: ^1.0.0

# TODO: If you want to contribute to dependency_overrides, add a pubspec_overrides.yaml file
# in this folder, containing the following:
dependency_overrides:
  app_analyzer_plugin:
    path: /Users/huangrong/barry/own/flutter-diy/app_analyzer_plugin