name: analyzer_exploration
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  analyzer: ^8.4.0
  args: ^2.7.0
  cli_completion: ^0.5.1
  code_builder: ^4.11.0
  dart_style: ^3.1.1
  mason_logger: ^0.3.3
  path: ^1.9.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.7.1
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.25.6
  very_good_analysis: ^10.0.0

executables:
  analyzer_exploration:
